apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  name: mysql-viewer
  namespace: default
spec:
  rules:
  - services: ["mysqldb.default.svc.cluster.local"]
    constraints:
    - key: "destination.port"
      values: ["3306"]
---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRoleBinding
metadata:
  name: bind-mysql-viewer
  namespace: default
spec:
  subjects:
  - user: "cluster.local/ns/default/sa/bookinfo-ratings"
  roleRef:
    kind: ServiceRole
    name: "mysql-viewer"
---
